name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ compiler
      run: sudo apt-get install -y g++

    - name: Build the project
      run: |
        cd src
        make
        echo "Creating directory for the binary"
        cd ..
        mkdir -p artifacts/usr/bin
        echo "Copying binary file to the artifacts directory"
        cp src/main artifacts/usr/bin/
        echo "List contents of artifacts/usr/bin"
        ls -l artifacts/usr/bin/

    - name: Run tests
      run: |
        chmod +x cicd/test_script.sh
        cd artifacts/usr/bin  # Переходим в папку с бинарником
        ../cicd/test_script.sh

    - name: Build .deb package
      run: |
        dpkg-buildpackage -us -uc
        mkdir -p artifacts/deb
        mv ../*.deb artifacts/deb/

    - name: Upload .deb package artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: artifacts/deb/*.deb
