name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ compiler
      run: sudo apt-get install -y g++

    - name: Build the project
      run: |
        make
        mkdir -p artifacts/usr/bin
        cp main artifacts/usr/bin/

    - name: Run tests
      run: |
        chmod +x cicd/test_script.sh
        cicd/test_script.sh

    - name: Build .deb package
      run: |
        dpkg-buildpackage -us -uc
        mkdir -p artifacts/deb
        mv ../*.deb artifacts/deb/

    - name: Upload .deb package artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: artifacts/deb/*.deb
